// Pricing snapshot for the Cartridge Economics calculator.
//
// Every preset carries the date it was checked and the public source URL so
// the page stays deterministic, offline capable and auditable. Prices are
// NEVER scraped at runtime. When a provider does not publish a price for a
// cost component (e.g. RunPod network-storage transfer), the component is
// listed in `unmodeled` and left null instead of being silently assumed zero.

const CARTRIDGE_PRICING = {
    snapshotDate: '2026-07-17',
    staleAfterDays: 90,

    gpu: [
        {
            id: 'runpod-h100-sxm-community',
            provider: 'RunPod',
            hardware: 'H100 SXM (Community Cloud)',
            price: 2.69,
            unit: 'USD/GPU-hour',
            checkedDate: '2026-07-17',
            sourceUrl: 'https://www.runpod.io/gpu-models/h100-sxm',
            notes: 'Community cloud tier',
        },
        {
            id: 'runpod-h100-sxm-secure',
            provider: 'RunPod',
            hardware: 'H100 SXM (Secure Cloud)',
            price: 2.99,
            unit: 'USD/GPU-hour',
            checkedDate: '2026-07-17',
            sourceUrl: 'https://www.runpod.io/gpu-models/h100-sxm',
            notes: 'Secure cloud tier',
        },
        {
            id: 'runpod-h200-community',
            provider: 'RunPod',
            hardware: 'H200 (Community Cloud)',
            price: 3.59,
            unit: 'USD/GPU-hour',
            checkedDate: '2026-07-17',
            sourceUrl: 'https://www.runpod.io/pricing',
            notes: 'Community cloud tier',
        },
        {
            id: 'runpod-h200-secure',
            provider: 'RunPod',
            hardware: 'H200 (Secure Cloud)',
            price: 4.39,
            unit: 'USD/GPU-hour',
            checkedDate: '2026-07-17',
            sourceUrl: 'https://www.runpod.io/pricing',
            notes: 'Secure cloud tier',
        },
        {
            id: 'lambda-h100-pcie',
            provider: 'Lambda',
            hardware: 'H100 PCIe',
            price: 3.29,
            unit: 'USD/GPU-hour',
            checkedDate: '2026-07-17',
            sourceUrl: 'https://lambda.ai/pricing',
            notes: 'On-demand',
        },
        {
            id: 'lambda-h100-sxm',
            provider: 'Lambda',
            hardware: 'H100 SXM',
            price: 4.29,
            unit: 'USD/GPU-hour',
            checkedDate: '2026-07-17',
            sourceUrl: 'https://lambda.ai/pricing',
            notes: 'On-demand',
        },
        {
            id: 'lambda-b200',
            provider: 'Lambda',
            hardware: 'B200 (single-GPU instance)',
            price: 6.99,
            unit: 'USD/GPU-hour',
            checkedDate: '2026-07-17',
            sourceUrl: 'https://lambda.ai/pricing',
            notes: 'CAS trained on H200/B200-class hardware',
        },
        {
            id: 'crusoe-h100-hgx',
            provider: 'Crusoe',
            hardware: 'H100 HGX',
            price: 3.9,
            unit: 'USD/GPU-hour',
            checkedDate: '2026-07-17',
            sourceUrl: 'https://www.crusoe.ai/cloud/pricing',
            notes: 'On-demand',
        },
        {
            id: 'crusoe-h200-hgx',
            provider: 'Crusoe',
            hardware: 'H200 HGX',
            price: 4.29,
            unit: 'USD/GPU-hour',
            checkedDate: '2026-07-17',
            sourceUrl: 'https://www.crusoe.ai/cloud/pricing',
            notes: 'On-demand',
        },
        {
            id: 'custom-gpu',
            provider: 'Custom',
            hardware: 'Custom GPU rate',
            price: null,
            unit: 'USD/GPU-hour',
            checkedDate: '2026-07-17',
            sourceUrl: 'https://github.com/mcgrof/kvcache-view',
            notes: 'User-supplied rate',
        },
    ],

    storage: [
        {
            id: 'r2-standard',
            provider: 'Cloudflare',
            storageClass: 'R2 Standard',
            usdPerGBMonth: 0.015,
            getUsdPerRequest: 0.36 / 1e6,
            retrievalUsdPerGB: 0,
            egressUsdPerGB: 0,
            unmodeled: [],
            unit: 'USD/GB-month',
            checkedDate: '2026-07-17',
            sourceUrl: 'https://developers.cloudflare.com/r2/pricing/',
            notes: '$0.36 per million Class B reads, no retrieval fee, no egress fee',
        },
        {
            id: 'r2-infrequent',
            provider: 'Cloudflare',
            storageClass: 'R2 Infrequent Access',
            usdPerGBMonth: 0.01,
            getUsdPerRequest: 0.9 / 1e6,
            retrievalUsdPerGB: 0.01,
            egressUsdPerGB: 0,
            unmodeled: [],
            unit: 'USD/GB-month',
            checkedDate: '2026-07-17',
            sourceUrl: 'https://developers.cloudflare.com/r2/pricing/',
            notes: '$0.90 per million Class B reads, $0.01/GB retrieval, no egress fee, 30-day minimum',
        },
        {
            id: 'backblaze-b2',
            provider: 'Backblaze',
            storageClass: 'B2 Cloud Storage',
            usdPerGBMonth: 0.00695,
            getUsdPerRequest: 0,
            retrievalUsdPerGB: 0,
            egressUsdPerGB: 0,
            egressOverageUsdPerGB: 0.01,
            unmodeled: [],
            unit: 'USD/GB-month',
            checkedDate: '2026-07-17',
            sourceUrl: 'https://www.backblaze.com/cloud-storage/pricing',
            notes:
                'Class A/B/C operations currently free; egress free up to 3x monthly stored volume, ' +
                '$0.01/GB beyond that (advanced override)',
        },
        {
            id: 'runpod-network-standard',
            provider: 'RunPod',
            storageClass: 'Network Storage Standard',
            usdPerGBMonth: null,
            tiers: [
                { minGB: 0, usdPerGBMonth: 0.07 },
                { minGB: 1000, usdPerGBMonth: 0.05 },
            ],
            getUsdPerRequest: null,
            retrievalUsdPerGB: null,
            egressUsdPerGB: null,
            unmodeled: ['getUsdPerRequest', 'retrievalUsdPerGB', 'egressUsdPerGB'],
            unit: 'USD/GB-month',
            checkedDate: '2026-07-17',
            sourceUrl: 'https://www.runpod.io/pricing',
            notes: '$0.07/GB-month below 1 TB, $0.05/GB-month at or above; transfer/request costs not published',
        },
        {
            id: 'runpod-network-hp',
            provider: 'RunPod',
            storageClass: 'Network Storage High Performance',
            usdPerGBMonth: 0.14,
            getUsdPerRequest: null,
            retrievalUsdPerGB: null,
            egressUsdPerGB: null,
            unmodeled: ['getUsdPerRequest', 'retrievalUsdPerGB', 'egressUsdPerGB'],
            unit: 'USD/GB-month',
            checkedDate: '2026-07-17',
            sourceUrl: 'https://www.runpod.io/pricing',
            notes: 'Transfer/request costs not published',
        },
        {
            id: 'custom-storage',
            provider: 'Custom',
            storageClass: 'Custom storage rates',
            usdPerGBMonth: null,
            getUsdPerRequest: null,
            retrievalUsdPerGB: null,
            egressUsdPerGB: null,
            unmodeled: [],
            unit: 'USD/GB-month',
            checkedDate: '2026-07-17',
            sourceUrl: 'https://github.com/mcgrof/kvcache-view',
            notes: 'User-supplied rates',
        },
    ],
}

if (typeof module !== 'undefined' && module.exports) {
    module.exports = CARTRIDGE_PRICING
}
